#include "OgreStateParameter.h"

using namespace LWP::Math;

void OgreState::ParameterConfig::InitJson()
{

	json.Init("OgreParameter.json");

	json.BeginGroup("OgreParameter")
		.AddValue("ExtrusionDist", &stateParameter_.extrusionDist)
		.BeginGroup("Idle")
		.AddValue("StandTime", &stateParameter_.idleParameter.standTime)
		.AddValue("MinStandTime", &stateParameter_.idleParameter.minStandTime)
		.AddValue("FollowingDist", &stateParameter_.idleParameter.followingDist)
		.EndGroup()
		.BeginGroup("Move")
		.AddValue("AttackDist", &stateParameter_.moveParameter.attackDist)
		.AddValue("RunTime", &stateParameter_.moveParameter.runTime)
		.AddValue("JumpAttackLimit", &stateParameter_.moveParameter.jumpAttackLimit)
		.AddValue("DefaultSpeed", &stateParameter_.moveParameter.defaultSpeed)
		.AddValue("LightTransitionCount", &stateParameter_.moveParameter.lightTransitionCount)
		.AddValue("MediumTransitionCount", &stateParameter_.moveParameter.mediumTransitionCount)
		.EndGroup()
		.BeginGroup("SwingDownAttack")
		.AddValue("StartAcceptTime", &stateParameter_.swingDownAttack.attackData.startAcceptTime)
		.AddValue("EndAcceptTime", &stateParameter_.swingDownAttack.attackData.endAcceptTime)
		.AddValue("EndMotionTime", &stateParameter_.swingDownAttack.attackData.endMotionTime)
		.AddValue("AttackPosition", &stateParameter_.swingDownAttack.attackData.attackPosition)
		.AddValue("AttackScale", &stateParameter_.swingDownAttack.attackData.attackScale)
		.AddValue("MoveSpeed", &stateParameter_.swingDownAttack.attackData.moveSpeed)
		.AddValue("AttackDistance", &stateParameter_.swingDownAttack.attackData.attackDistance)
		.AddValue("SEPlayTime", &stateParameter_.swingDownAttack.attackData.sePlayTime)
		.AddValue("EffectPosition", &stateParameter_.swingDownAttack.effectParam.position)
		.AddValue("EffectRotate", &stateParameter_.swingDownAttack.effectParam.rotate)
		.AddValue("EffectScale", &stateParameter_.swingDownAttack.effectParam.scale)
		.AddValue("EffectPlayTime", &stateParameter_.swingDownAttack.effectParam.playTime)
		.AddValue("EffectOffset", &stateParameter_.swingDownAttack.effectParam.offset)
		.AddValue("EffectColor", &stateParameter_.swingDownAttack.effectParam.color)
		.EndGroup()
		.BeginGroup("RotatingSlash")
		.AddValue("StartAcceptTime", &stateParameter_.rotatingSlash.attackData.startAcceptTime)
		.AddValue("EndAcceptTime", &stateParameter_.rotatingSlash.attackData.endAcceptTime)
		.AddValue("EndMotionTime", &stateParameter_.rotatingSlash.attackData.endMotionTime)
		.AddValue("AttackPosition", &stateParameter_.rotatingSlash.attackData.attackPosition)
		.AddValue("AttackScale", &stateParameter_.rotatingSlash.attackData.attackScale)
		.AddValue("MoveSpeed", &stateParameter_.rotatingSlash.attackData.moveSpeed)
		.AddValue("AttackDistance", &stateParameter_.rotatingSlash.attackData.attackDistance)
		.AddValue("SEPlayTime", &stateParameter_.rotatingSlash.attackData.sePlayTime)
		.AddValue("EffectPosition", &stateParameter_.rotatingSlash.effectParam.position)
		.AddValue("EffectRotate", &stateParameter_.rotatingSlash.effectParam.rotate)
		.AddValue("EffectScale", &stateParameter_.rotatingSlash.effectParam.scale)
		.AddValue("EffectPlayTime", &stateParameter_.rotatingSlash.effectParam.playTime)
		.AddValue("EffectOffset", &stateParameter_.rotatingSlash.effectParam.offset)
		.AddValue("EffectColor", &stateParameter_.rotatingSlash.effectParam.color)
		.EndGroup()
		.BeginGroup("FallingThrust")
		.AddValue("StartAcceptTime", &stateParameter_.fallingThrust.attackData.startAcceptTime)
		.AddValue("EndAcceptTime", &stateParameter_.fallingThrust.attackData.endAcceptTime)
		.AddValue("EndMotionTime", &stateParameter_.fallingThrust.attackData.endMotionTime)
		.AddValue("AttackPosition", &stateParameter_.fallingThrust.attackData.attackPosition)
		.AddValue("AttackScale", &stateParameter_.fallingThrust.attackData.attackScale)
		.AddValue("SEPlayTime", &stateParameter_.fallingThrust.attackData.sePlayTime)
		.AddValue("JumpWaitingTime", &stateParameter_.fallingThrust.jumpWaitingTime)
		.AddValue("JumpingTime", &stateParameter_.fallingThrust.jumpingTime)
		.AddValue("FallWaitingTime", &stateParameter_.fallingThrust.fallWaitingTime)
		.AddValue("FallingTime", &stateParameter_.fallingThrust.fallingTime)
		.AddValue("AttackTime", &stateParameter_.fallingThrust.attackTime)
		.AddValue("GapTime", &stateParameter_.fallingThrust.gapTime)
		.AddValue("JumpingHeight", &stateParameter_.fallingThrust.jumpingHeight)
		.EndGroup()
		.BeginGroup("AssaultSlash")
		.AddValue("AttackPosition", &stateParameter_.assaultSlash.attackData.attackPosition)
		.AddValue("AttackScale", &stateParameter_.assaultSlash.attackData.attackScale)
		.AddValue("StartSEPlayTime", &stateParameter_.assaultSlash.startSEPlayTime)
		.AddValue("SEPlayTime", &stateParameter_.assaultSlash.attackData.sePlayTime)
		.AddValue("LeaveDistance", &stateParameter_.assaultSlash.leaveDistance)
		.AddValue("OverDistance", &stateParameter_.assaultSlash.overDistance)
		.AddValue("DivingTime", &stateParameter_.assaultSlash.divingTime)
		.AddValue("StealthWaitingTime", &stateParameter_.assaultSlash.stealthWaitingTime)
		.AddValue("WaitingTime", &stateParameter_.assaultSlash.waitingTime)
		.AddValue("AssaultTime", &stateParameter_.assaultSlash.assaultTime)
		.AddValue("GapTime", &stateParameter_.assaultSlash.gapTime)
		.AddValue("EffectPosition", &stateParameter_.assaultSlash.effectParam.position)
		.AddValue("EffectRotate", &stateParameter_.assaultSlash.effectParam.rotate)
		.AddValue("EffectScale", &stateParameter_.assaultSlash.effectParam.scale)
		.AddValue("EffectPlayTime", &stateParameter_.assaultSlash.effectParam.playTime)
		.AddValue("EffectOffset", &stateParameter_.assaultSlash.effectParam.offset)
		.AddValue("EffectColor", &stateParameter_.assaultSlash.effectParam.color)
		.EndGroup()
		.BeginGroup("QuadrupleAttack");

		for (int32_t i = 0; i < stateParameter_.quadrupleAttack.kMaxAttackCount; i++) {

			std::string numStr = std::to_string(i + 1);

			json.AddValue("StartAcceptTime" + numStr, &stateParameter_.quadrupleAttack.multipleAttackData[i].startAcceptTime)
				.AddValue("EndAcceptTime" + numStr, &stateParameter_.quadrupleAttack.multipleAttackData[i].endAcceptTime)
				.AddValue("EndMotionTime" + numStr, &stateParameter_.quadrupleAttack.multipleAttackData[i].endMotionTime)
				.AddValue("AttackPosition" + numStr, &stateParameter_.quadrupleAttack.multipleAttackData[i].attackPosition)
				.AddValue("AttackScale" + numStr, &stateParameter_.quadrupleAttack.multipleAttackData[i].attackScale)
				.AddValue("MoveSpeed" + numStr, &stateParameter_.quadrupleAttack.multipleAttackData[i].moveSpeed)
				.AddValue("AttackDistance" + numStr, &stateParameter_.quadrupleAttack.multipleAttackData[i].attackDistance)
				.AddValue("SEPlayTime" + numStr, &stateParameter_.quadrupleAttack.multipleAttackData[i].sePlayTime)
				.AddValue("EffectPosition" + numStr, &stateParameter_.quadrupleAttack.effectParam[i].position)
				.AddValue("EffectRotate" + numStr, &stateParameter_.quadrupleAttack.effectParam[i].rotate)
				.AddValue("EffectScale" + numStr, &stateParameter_.quadrupleAttack.effectParam[i].scale)
				.AddValue("EffectPlayTime" + numStr, &stateParameter_.quadrupleAttack.effectParam[i].playTime)
				.AddValue("EffectOffset" + numStr, &stateParameter_.quadrupleAttack.effectParam[i].offset)
				.AddValue("EffectColor" + numStr, &stateParameter_.quadrupleAttack.effectParam[i].color);

		}

		json.EndGroup()
		.BeginGroup("HitReaction")
		.AddValue("Decay", &stateParameter_.hitReactionParameter.decay)
		.EndGroup()
		.BeginGroup("Dead")
		.AddValue("StepBackSpeed", &stateParameter_.deadParameter.stepBackSpeed)
		.AddValue("BackStartFirst", &stateParameter_.deadParameter.backStartF)
		.AddValue("BackEndFirst", &stateParameter_.deadParameter.backEndF)
		.AddValue("BackStartSecond", &stateParameter_.deadParameter.backStartS)
		.AddValue("BackEndSecond", &stateParameter_.deadParameter.backEndS)
		.EndGroup()
		.BeginGroup("SpawnEnemy")
		.AddValue("SEPlayTime", &stateParameter_.spawnEnemy.sePlayTime)
		.EndGroup()
		.EndGroup()
		.CheckJsonFile();

}
